---
name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ["1.17", "1.18"]
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Make build for testing
        run: make

      - name: Run with empty args
        run: ./indiepkg

      - name: Run help command
        run: ./indiepkg help

      - name: Run setup command
        run: ./indiepkg setup -d
      
      - name: Run github-gen command
        run: ./indiepkg github-gen talwat indiepkg -d

      - name: Install a few packages
        run: ./indiepkg install treefetch pfetch yaf skyfetch ne neofetch -y -d

      - name: Test installed packages
        continue-on-error: true
        run: |
          $HOME/.local/bin/pfetch
          $HOME/.local/bin/treefetch
          $HOME/.local/bin/yaf
          $HOME/.local/bin/skyfetch
          $HOME/.local/bin/ne --help

      - name: Force upgrade packages
        run: |
          ./indiepkg upgrade -f -d
          ./indiepkg upgrade treefetch pfetch yaf skyfetch ne neofetch -f -d

      - name: Update packages
        run: |
          ./indiepkg update -d
          ./indiepkg upgrade treefetch pfetch yaf skyfetch ne neofetch -d

      - name: Add repo
        run: ./indiepkg repo add https://raw.githubusercontent.com/talwat/indiepkg/main/packages/linux-only/

      - name: List repos
        run: ./indiepkg repo list

      - name: Test querying
        continue-on-error: true
        run: ./indiepkg search fetch

      - name: Try installing package from linux-only
        run: ./indiepkg install katfetch -y -d

      - name: List packages
        run: ./indiepkg list

      - name: Uninstall package with --purge
        run: ./indiepkg uninstall neofetch -p -y

      - name: Uninstall other packages
        run: ./indiepkg uninstall treefetch pfetch yaf -y -d

      - name: Try other commands
        run: |
          ./indiepkg sync
          ./indiepkg info btop
          ./indiepkg remove-data btop -y -d
          ./indiepkg version

      - name: Try manually updating IndiePKG
        run: |
          ./indiepkg indiepkg-update
